server:
  port: 9998
---
spring:
  profiles:
    active: local
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: pwd
    driver-class-name: org.h2.Driver
  batch:
    job:
      enabled: false